//
//  ChannelInteractor.swift
//  FireChat
//
//  Created by Ngoc Tuan Le on 12/10/18.
//  Copyright (c) 2018 LifeOfCoder. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ChannelInteractor {
}

// MARK: - Extensions -

extension ChannelInteractor: ChannelInteractorInterface {
}
