//
//  ChannelPresenter.swift
//  FireChat
//
//  Created by Ngoc Tuan Le on 12/10/18.
//  Copyright (c) 2018 LifeOfCoder. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ChannelPresenter {

    // MARK: - Private properties -

    private unowned let _view: ChannelViewInterface
    private let _wireframe: ChannelWireframeInterface
    private let _interactor: ChannelInteractorInterface

    // MARK: - Lifecycle -

    init(wireframe: ChannelWireframeInterface, view: ChannelViewInterface, interactor: ChannelInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension ChannelPresenter: ChannelPresenterInterface {
}
