//
//  ChannelViewController.swift
//  FireChat
//
//  Created by Ngoc Tuan Le on 12/10/18.
//  Copyright (c) 2018 LifeOfCoder. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ChannelViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: ChannelPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }
	
}

// MARK: - Extensions -

extension ChannelViewController: ChannelViewInterface {
}
