//
//  LoginModels.swift
//  FireChat
//
//  Created by Ngoc Tuan Le on 9/30/18.
//  Copyright (c) 2018 LifeOfCoder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
  
  enum FacebookLogin
  {
    struct Request
    {
        var token: String
    }
    struct Response
    {
        
    }
    struct ViewModel
    {
    }
  }
}
