//
//  LoginPresenter.swift
//  FireChat
//
//  Created by Ngoc Tuan Le on 9/30/18.
//  Copyright (c) 2018 LifeOfCoder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
  func presentSomething(response: Login.FacebookLogin.Response)
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Login.FacebookLogin.Response)
  {
    let viewModel = Login.FacebookLogin.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
