//
//  LoginInteractor.swift
//  FireChat
//
//  Created by Ngoc Tuan Le on 12/9/18.
//  Copyright (c) 2018 LifeOfCoder. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation


final class LoginInteractor {
    
    private var _userService = UserService()
}

// MARK: - Extensions -

extension LoginInteractor: LoginInteractorInterface {
    
    func signInAnonymously(completion: @escaping LoginCompletionBlock) {
        _userService.signInAnonymously(completion: completion)
    }

}
